### ISSUE TITLE
Question on design

### ISSUE THREAD

**Issue by kaithar** [ianbarber/TLSZMQ#2]
Is there a particular rational behind writing the code as a "third party helper" ... not sure what the best term is actually ... instead of transparently wrapping the socket?

From a quick look over the code it seems as though it could be modified easily enough to not require the manual pass in/pass out mechanics, but rather give it the socket and let the tls class do the reading/writing to zmq.
Doing it as a wrapper does lose some flexibility in packet format, but not too much... you'd either have to build the envelope as (ID,Null,Encrypted payload) or prepend/append the payload like (ID, Null, [[arbitary, Null], ...], Encrypted payload).  Essentially sacrificing flexibility for code reduction.

As I'm following the code, the input is wrapped in zmq message objects, but it's actually processing it on the basis of a binary stream... that would need to be adjusted for more complicated multipart messages?
I'm not seeing anything to handle message delimiting either ... is it a safe assumption that this code is intended for emulating a stream rather than datagram series, with all the messages being concated together and splitting being purely based on how much of the message has been decoded when you ask if it has data?

What's your thoughts on using an inproc transport for passing data in and out of the tls code?
Something like creating the desired type of ZMQ socket and throwing it off in to a worker thread, then talking to the worker over inproc... the worker takes packets in, strips the envelope, encrypts/decrypts the payload, puts the envelope back on, then passes it off to the socket on other side.  Success would likely vary with socket type, ROUTER and PUB/SUB should work well, REQ/REP and PUSH/PULL might not be so good.

**Comment by ianbarber** [comment]
This was mainly designed as an example, so the logic of having it as a helper was in order to show that. Wrapping it transparently seems very sensible, and using inproc to expose an internal service that handled the transport seems fairly sensible.

Handle multiple message parts should be a fairly trivial addition as you say.

**Comment by vpnwr** [comment]
I initially cooked up a version of TLSZmq that takes in a zmq::socket_t and does all the IO internally (encapsulates all handshake and renegotiation etc). Leaving a clean interface for the clients. While it works great with a REQ/RES pattern, it doesn't work so well with a ROUTER. The server sitting on a ROUTER socket, needs to manage 1 TLS object per client while all network IO is multiplexed over the same socket.

I don't have an elegant way to solve this yet.

-Vikas
