### ISSUE TITLE
a little question about your code

### ISSUE THREAD

**Issue by ChenYue1127** [ianbarber/TLSZMQ#8]
Firstly, I have to say that your code really do me a big favour during my recent  work. Thanks a lot. 

I got a little problem trying to understand some specific sentences in your project----- "socket->send( *request, ZMQ_SNDMORE );",  In read_message(...) of the file tlsserver.cpp. In my opinion, the content of "request"  is the sender identity(according to the comments), why we have to send it back to the sender? Does it associate  with the ssl handshake ? 

May be I take it in a wrong way, hope that you can give me some tips to help me understand it right.

Thanks for your time.

**Comment by ianbarber** [comment]
Been a while since I looked at that code, but its probably because the socket is a router - you need to tell it which connection to send via. See http://zguide.zeromq.org/php:chapter3#header-68

**Comment by ChenYue1127** [comment]
Thanks for your last answer, it really does help.

Sorry to bother again .Here I got another issue 
when I step debug your code, I find that ssl handshake process is implemented when SSL_write() and SSL_read() are called, using while-loop to help send handshake messages. (Hope I take it right.)

Does it means that the server and client need to do handshake every time when there is a message need to be send ?
